apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "relname" . }}-csproxy
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "relname" . }}
    component: csproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "relname" . }}
      component: csproxy
  template:
    metadata:
      labels:
        app: {{ template "relname" . }}
        component: csproxy
    spec:
      containers:
      - name: {{ template "relname" . }}-csproxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.17
        imagePullPolicy: Always
        command:
        - /cloud_sql_proxy
        - -instances={{ .Values.postgresql.connectionName }}=tcp:0.0.0.0:{{ .Values.postgresql.port }}
        - -credential_file=/tmp/secrets/google_sa.json
        ports:
        - containerPort: {{ .Values.postgresql.port }}
          name: http-csp
        volumeMounts:
        - name: secrets
          mountPath: /tmp/secrets
          readOnly: true
        # livenessProbe:
        #   httpGet:
        #     path: /live
        #     port: {{ .Values.ports.sternguard }}
        #   initialDelaySeconds: 10
        #   periodSeconds: 3
        # readinessProbe:
        #   httpGet:
        #     path: /ready
        #     port: {{ .Values.ports.sternguard }}
        #   initialDelaySeconds: 10
        #   periodSeconds: 3
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      volumes:
      - name: secrets
        secret:
          secretName: {{ template "relname" . }}-shared-vol
---
{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "relname" . }}-csproxy-hpa
  labels:
    app: {{ template "relname" . }}
    component: hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "relname" . }}-csproxy
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
{{- end }}
