apiVersion: v1
kind: Service
metadata:
  name: {{ template "relname" . }}-notification
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "relname" . }}
    component: notification      
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: {{ .Values.ports.notification }}
    protocol: TCP
    name: http-notif
  selector:
    app: {{ template "relname" . }}
    component: notification
